[build-system]
requires = ["setuptools>=64.0.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "cmpl"
version = "0.5.0"
description = "CMRR MRI Processing Libraries"
authors = [{name = "Eisa Hedayati,", email = "heday015@umn.edu"}]
dependencies = [
    "numpy>=1.9.0",
    "scipy>=1.10.0",
    "pandas>=2.0.0",
    "h5py>=3.0.0",
    "pydicom>=2.0.0",
    "nibabel>=5.0.0",
    "pytest>=8.0.0",
    "hypothesis>=6.0.0"
]
